[build-system]
requires = ["setuptools>=78.0"]
build-backend = "setuptools.build_meta"

[project]
name = "readme-agent"
version = "0.0.1"
description = "AI agent that creates a README file for a GitHub repo"
requires-python = ">=3.12"
dependencies = []
